import Head from 'next/head';
import type { AppProps } from 'next/app';
import '@/styles/globals.css';

import Navbar from '@/components/Navbar';
import AppProvider from '@/components/context';

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Supabase Demo App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <AppProvider>
        <div className='bg-black min-h-screen'>
          <Navbar />
          <section className='pt-10'>
            <Component {...pageProps} />
          </section>
        </div>
      </AppProvider>
    </>
  );
}
