import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Supabase Demo App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='p-5'>
        <h2 className='text-blue-600 text-3xl font-semibold'>
          Supabase demo app
        </h2>
      </main>
    </>
  );
}
